---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cf-deployer
rules:
- apiGroups:
  - ""
  - apiextensions.k8s.io
  - networking.k8s.io
  - apps
  - jobs
  - rbac.authorization.k8s.io
  - policy
  - batch
  - scheduling.k8s.io
  - kpack.io
  - networking.istio.io
  - apps.cloudfoundry.org
  - security.istio.io
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-deployer
subjects:
- kind: ServiceAccount
  name: cf-deployer
  namespace: default
